//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogosSystem.Models.Repository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        public int Aluno_ID { get; set; }
        public string PrimeiroNome { get; set; }
        public string SegundoNome { get; set; }
        public string Igreja { get; set; }
        public Nullable<int> Idade { get; set; }
    }
}
