
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LogosSystem.Models.Repository.Database
{

using System;
    using System.Collections.Generic;
    
public partial class falta
{

    public int Falta_ID { get; set; }

    public int Quantidade { get; set; }

    public int Aluno_ID { get; set; }

    public int Disciplina_ID { get; set; }



    public virtual aluno aluno { get; set; }

    public virtual disciplina disciplina { get; set; }

}

}
