

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LogosSystem.Models.Repository.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class logossystemEntities : DbContext
{
    public logossystemEntities()
        : base("name=logossystemEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<aluno> aluno { get; set; }

    public virtual DbSet<curso> curso { get; set; }

    public virtual DbSet<diretor> diretor { get; set; }

    public virtual DbSet<disciplina> disciplina { get; set; }

    public virtual DbSet<falta> falta { get; set; }

    public virtual DbSet<igreja> igreja { get; set; }

    public virtual DbSet<instituicao> instituicao { get; set; }

    public virtual DbSet<localizacao> localizacao { get; set; }

    public virtual DbSet<nacao> nacao { get; set; }

    public virtual DbSet<nota> nota { get; set; }

    public virtual DbSet<pastor> pastor { get; set; }

    public virtual DbSet<professor> professor { get; set; }

    public virtual DbSet<turma> turma { get; set; }

    public virtual DbSet<aluno_cursos> aluno_cursos { get; set; }

    public virtual DbSet<professor_cursos> professor_cursos { get; set; }

}

}

