
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LogosSystem.Models.Repository.Database
{

using System;
    using System.Collections.Generic;
    
public partial class pastor
{

    public int Pastor_ID { get; set; }

    public string Primeiro_Nome { get; set; }

    public string Segundo_Nome { get; set; }

    public System.DateTime Data_Nascimento { get; set; }

    public string Email { get; set; }

    public string Telefone { get; set; }

    public string Celular { get; set; }

    public string RG { get; set; }

    public string CPF { get; set; }

    public int Nacao_ID { get; set; }

    public int Idade { get; set; }

    public int Sexo { get; set; }

    public Nullable<int> Estado_Civil { get; set; }

    public string Conjuge_Nome { get; set; }

    public int Igreja_ID { get; set; }



    public virtual igreja igreja { get; set; }

}

}
