
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LogosSystem.Models.Repository.Database
{

using System;
    using System.Collections.Generic;
    
public partial class professor
{

    public int Professor_ID { get; set; }

    public string Primeiro_Nome { get; set; }

    public string Segundo_Nome { get; set; }

    public System.DateTime Data_Nascimento { get; set; }

    public string Email { get; set; }

    public Nullable<int> Area_Ensino { get; set; }

    public string Telefone { get; set; }

    public string Celular { get; set; }

    public string RG { get; set; }

    public string CPF { get; set; }

    public int Nacao_ID { get; set; }

    public string CidadeNascimento { get; set; }

    public int Idade { get; set; }

    public int Sexo { get; set; }

    public string Pai_Nome { get; set; }

    public string Mae_Nome { get; set; }

    public string EnderecoComercial { get; set; }

    public string TelefoneComercial { get; set; }

    public string Profissao { get; set; }

    public Nullable<int> Estado_Civil { get; set; }

    public Nullable<int> Estado_Civil_Antigo { get; set; }

    public Nullable<int> Filhos_Qtt { get; set; }

    public string Conjuge_Nome { get; set; }

    public Nullable<bool> Has_Tabaco { get; set; }

    public Nullable<bool> Has_Toxicos { get; set; }

    public Nullable<bool> Is_Sociedade_Secreta { get; set; }

    public Nullable<bool> Has_Ensino_Fundamental { get; set; }

    public Nullable<bool> Has_Ensino_Medio { get; set; }

    public Nullable<bool> Has_Ensino_Superior { get; set; }

    public string Outros_Cursos { get; set; }

    public string Formacao_Descricao { get; set; }

    public bool Is_Ativo { get; set; }



    public virtual nacao nacao { get; set; }

}

}
